name: 'Submit to intra.42.fr'
description: 'Submits the specified subfolder of the repo to the intranet'
inputs:
  code-to-submit:
    description: 'The subfolder of your github repo to submit to the intranet, the whole repo is submitted by default'
    required: true
    default: '.'
  intra-repo:
    description: 'Git repository link on your project page'
    required: true
  intra-ssh-key:
    description: 'Your private key to the intranet; set a separate one for this action'
    required: true
  commit-message:
    description: 'Commit message for the intranet submission; by default the last one from the active branch is used'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: github-repo
        persist-credentials: false
    - run: eval `ssh-agent`; echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> "$GITHUB_ENV"
      shell: bash
    - run: echo {{ env.SSH_AUTH_SOCK }}
      shell: bash
    - run: echo "${INTRA_SSH_KEY}" | ssh-add -
      shell: bash
      env:
        INTRA_SSH_KEY: ${{ inputs.intra-ssh-key }}
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
    - run: git clone "$INTRA_REPO_URL" intra-repo
      shell: bash
      env:
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        INRA_REPO_URL: ${{ intra.INRA_REPO_URL }}
    - run: cat intra-repo/README.md
      shell: bash
    - run: echo "SSH_AUTH_SOCK=" >> "$GITHUB_ENV"
      shell: bash
