name: 'Submit to intra.42.fr'
description: 'Submits the specified subfolder of the repo to the intranet'
inputs:
  code-to-submit:
    description: 'Folder to submit to the intranet, the whole repo is submitted by default'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: github-repo
    - run: git --no-pager log --pretty -1
      shell: bash
      working-directory: ./github-repo
